when:
  event:
    - push
    - manual

steps:
  - name: setup_container
    image: docker:24.0.5-cli

    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_TOKEN:
        from_secret: DOCKERHUB_TOKEN
      GIT_USER_NAME:
        from_secret: GIT_USER_NAME
      GIT_USER_EMAIL:
        from_secret: GIT_USER_EMAIL

    volumes:
      - name: dockersock
        path: /var/run/docker.sock

    commands:
      # Install only missing tools (no docker install!)
      - apk add --no-cache bash jq curl git

      # Verify Docker works
      - docker version

      # Go to repo root
      - cd "$CI_WORKSPACE"

      # Make scripts executable
      - chmod +x scripts/*.sh

      # Run scripts
      - ./scripts/git_setup.sh
      - ./scripts/docker_login.sh
      - ./scripts/validate_repo.sh
      - ./scripts/build_services.sh

volumes:
  dockersock:
    host:
      path: /var/run/docker.sock
