when:
  event:
    - push
    - manual

steps:
  - name: Set-up git
    image: alpine:latest
    environment:
      GIT_USER_NAME:
        from_secret: GIT_USER_NAME
      GIT_USER_EMAIL:
        from_secret: GIT_USER_EMAIL
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands: |
      cd "$CI_WORKSPACE"
      apk add --no-cache git

      git config user.name "$GIT_USER_NAME"
      git config user.email "$GIT_USER_EMAIL"

      git config --add safe.directory "$CI_WORKSPACE"

      git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$CI_REPO_OWNER/$CI_REPO_NAME.git
      git branch --set-upstream-to=origin/main main || true


  - name: Check services
    image: alpine:latest
    commands: |
      apk add --no-cache jq
      jq -r 'to_entries | sort_by(.value.order) | .[].key' services.json > services.order

  - name: Build and push containers
    image: docker:latest
    environment:
      DOCKER_CLIENT_TIMEOUT: 1800
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_TOKEN:
        from_secret: DOCKERHUB_TOKEN

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands: |
      apk add --no-cache jq git coreutils

      cd "$CI_WORKSPACE"


      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      while read service; do
        SERVICE_PATH="$CI_WORKSPACE/$service"
        HASH_FILE="$SERVICE_PATH/service_hash"

        CURRENT_HASH=$(sha256sum \
          "$SERVICE_PATH/Dockerfile" \
          "$SERVICE_PATH/build_firmware.sh" \
          "$SERVICE_PATH/build.sh" \
          | sha256sum | awk '{print $1}')

        FULL_REBUILD=false
        if [ ! -f "$HASH_FILE" ] || [ "$(cat "$HASH_FILE")" != "$CURRENT_HASH" ]; then
          FULL_REBUILD=true
        fi

        echo "$CURRENT_HASH" > "$HASH_FILE"
        git pull --rebase origin main
        git add "$HASH_FILE"
        git commit -m "CI: update service_hash for $service [skip ci]" || true
        git push origin HEAD || true

        jq -c '.[]' "$SERVICE_PATH/versions.json" > /tmp/versions.list

        while read obj; do
          VERSION=$(printf '%s\n' "$obj" | jq -r '.micropython')
          BUILT=$(printf '%s\n' "$obj" | jq -r '.built')

          if [ "$FULL_REBUILD" = "false" ] && [ "$BUILT" = "true" ]; then
            echo "[INFO] Skipping $service $VERSION"
            continue
          fi

          FLAGS=""
          for key in $(printf '%s\n' "$obj" | jq -r 'keys[]'); do
            value=$(printf '%s\n' "$obj" | jq -r --arg k "$key" '.[$k] | tostring')
            FLAGS="$FLAGS --$key $value"
          done

          FLAGS=$(printf '%s\n' "$FLAGS" | sed 's/--built [^ ]*//g')
          FLAGS="$FLAGS --built false"

          if sh "$SERVICE_PATH/build.sh" "$SERVICE_PATH" $FLAGS; then
            tmp=$(mktemp)
            jq --arg v "$VERSION" \
              'map(if .micropython == $v then .built = true else . end)' \
              "$SERVICE_PATH/versions.json" > "$tmp" && mv "$tmp" "$SERVICE_PATH/versions.json"

            git pull --rebase origin main
            git add "$SERVICE_PATH/versions.json"
            git commit -m "CI: mark $service $VERSION as built [skip ci]" || true
            git push origin HEAD || true
          fi
        done < /tmp/versions.list
      done < services.order

  - name: Update DockerHub documentation
    image: docker:latest
    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_TOKEN:
        from_secret: DOCKERHUB_TOKEN
    commands: |
      apk add --no-cache curl jq git
      cd "$CI_WORKSPACE"

      TOKEN=$(curl -s -X POST https://hub.docker.com/v2/users/login/ \
        -H "Content-Type: application/json" \
        -d "{\"username\":\"$DOCKERHUB_USERNAME\",\"password\":\"$DOCKERHUB_TOKEN\"}" \
        | jq -r .token)

      while read service; do
        README="$CI_WORKSPACE/$service/README.md"
        HASH_FILE="$CI_WORKSPACE/$service/readme_hash"

        [ -f "$README" ] || continue

        HASH=$(sha256sum "$README" | awk '{print $1}')
        [ -f "$HASH_FILE" ] && [ "$HASH" = "$(cat "$HASH_FILE")" ] && continue

        curl -s -X PATCH \
          "https://hub.docker.com/v2/repositories/$DOCKERHUB_USERNAME/$service/" \
          -H "Authorization: JWT $TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"full_description\": $(jq -Rs . < "$README")}" \
          > /dev/null

        echo "$HASH" > "$HASH_FILE"
        git pull --rebase origin main
        git add "$HASH_FILE"
        git commit -m "CI: update readme_hash for $service [skip ci]" || true
        git push origin HEAD || true
      done < services.order

  - name: Docker cleanup
    image: docker:latest
    environment:
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands: |
      docker image prune -f
      docker builder prune -f