# .woodpecker.yml
pipeline:
  build_containers:
    image: docker:27.2-git
    shell: bash
    environment:
      WORKSPACE: /var/containers
      ROOT: /var/containers
      GIT_USER_NAME: "Build Containers Bot"
      GIT_USER_EMAIL: "buildbot@example.com"
    secrets:
      - DOCKERHUB_USERNAME
      - DOCKERHUB_TOKEN
    vars: 
      - GIT_USER_NAME
      - GIT_USER_EMAIL
    commands:
      - apk add --no-cache bash jq curl git docker-cli

      # -------------------------------------------------
      # Git configuration
      # -------------------------------------------------
      - |
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_USER_EMAIL"
        git config --global --add safe.directory "$WORKSPACE"