when:
  event:
    - push
    - manual

steps:
  - name: build_and_push
    image: docker:latest
    privileged: true
    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_TOKEN:
        from_secret: DOCKERHUB_TOKEN

      GIT_USER_NAME:
        from_secret: GIT_USER_NAME
      GIT_USER_EMAIL:
        from_secret: GIT_USER_EMAIL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    commands:
      - apk add --no-cache bash jq curl git
      - docker version

      # Move to repo workspace
      - cd "$CI_WORKSPACE"

      # Make all scripts executable
      - chmod +x scripts/*.sh

      # Run your existing scripts
      - ./scripts/git_setup.sh
      - ./scripts/docker_login.sh
      - ./scripts/validate_repo.sh
      - ./scripts/build_services.sh