when:
  event:
    - push
    - manual

steps:
  - name: setup_container
    image: docker:24.0.5-cli

    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_TOKEN:
        from_secret: DOCKERHUB_TOKEN
      GIT_USER_NAME:
        from_secret: GIT_USER_NAME
      GIT_USER_EMAIL:
        from_secret: GIT_USER_EMAIL

    volumes:
      - name: dockersock
        path: /var/run/docker.sock

    commands:
      - apk add --no-cache bash jq curl git
      - docker version
      - cd "$CI_WORKSPACE"
      - chmod +x scripts/*.sh
      - ./scripts/git_setup.sh
      - ./scripts/docker_login.sh
      - ./scripts/validate_repo.sh
      - ./scripts/build_services.sh

volumes:
  dockersock:
    host:
      path: /var/run/docker.sock
