when:
  event:
    - push
    - manual

steps:
  setup_container:
    image: alpine:latest
    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_TOKEN:
        from_secret: DOCKERHUB_TOKEN
      GIT_USER_NAME:
        from_secret: GIT_USER_NAME
      GIT_USER_EMAIL:
        from_secret: GIT_USER_EMAIL
    commands:
      - apk add --no-cache bash jq curl git docker-cli

      # Change directory to the repo root (Woodpecker workspace)
      - cd "$CI_WORKSPACE"

      - chmod +x $CI_WORKSPACE/.woodpecker/scripts/*.sh

      - $CI_WORKSPACE/.woodpecker/scripts/git_setup.sh
      - $CI_WORKSPACE/.woodpecker/scripts/docker_login.sh
      - $CI_WORKSPACE/.woodpecker/scripts/validate_repo.sh
      - $CI_WORKSPACE/.woodpecker/scripts/build_services.sh