when:
  event:
    - push
    - manual

skip_clone: true

steps:
  setup_container:
    image: alpine:latest
    environment:
      WORKSPACE: /var/workspace
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_TOKEN:
        from_secret: DOCKERHUB_TOKEN
      GIT_USER_NAME:
        from_secret: GIT_USER_NAME
      GIT_USER_EMAIL:
        from_secret: GIT_USER_EMAIL
    commands:
      # Base tools
      - apk add --no-cache bash jq curl git docker-cli

      # Make scripts executable
      - chmod +x .woodpecker/scripts/*.sh

      # Run pipeline
      - .woodpecker/scripts/git_setup.sh
      - .woodpecker/scripts/clone_repo.sh
      - .woodpecker/scripts/docker_login.sh
      - .woodpecker/scripts/validate_repo.sh
      - .woodpecker/scripts/build_services.sh